// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzuWI3mjjwSLnjJbwEc0v0LvU9ounTEgc',
    appId: '1:799467205159:web:e29236f82e83073d81d402',
    messagingSenderId: '799467205159',
    projectId: 'cooking-app-db8d2',
    authDomain: 'cooking-app-db8d2.firebaseapp.com',
    storageBucket: 'cooking-app-db8d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPRBlxrooSwMV7pUY4se8YlazaCsH5XY',
    appId: '1:799467205159:android:3b67addb3555f44f81d402',
    messagingSenderId: '799467205159',
    projectId: 'cooking-app-db8d2',
    storageBucket: 'cooking-app-db8d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUO-YOr8jXKLLmX3io4Zu3SjXbQ2HxaAc',
    appId: '1:799467205159:ios:cc8f8e48cbf20f0181d402',
    messagingSenderId: '799467205159',
    projectId: 'cooking-app-db8d2',
    storageBucket: 'cooking-app-db8d2.appspot.com',
    iosBundleId: 'com.example.appCooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUO-YOr8jXKLLmX3io4Zu3SjXbQ2HxaAc',
    appId: '1:799467205159:ios:a5b89892bbc98ff881d402',
    messagingSenderId: '799467205159',
    projectId: 'cooking-app-db8d2',
    storageBucket: 'cooking-app-db8d2.appspot.com',
    iosBundleId: 'com.example.appCooking.RunnerTests',
  );
}
